/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ADC Noise Password Generator
 * Samples the NTC thermistor divider on PA0 (ADC1_IN0, temp) and the LDR
 * divider on PA1 (ADC1_IN1, light) as a physical entropy source. Each
 * raw bit is Von Neumann-debiased before use (see von_neumann_bit()),
 * since the raw ADC LSB is badly skewed (measured as far as 83%/17% on
 * real hardware) rather than 50/50. Eight debiased bits (alternating
 * temp/light) are packed into one 8-bit entropy byte, which is
 * rejection-sampled against the user's chosen character set (see
 * noisy_char_from_charset()) to remove the remaining rounding-edge bias
 * before being mapped onto a password character. Each generation run
 * asks which character classes to include and how many characters to
 * generate, and is continuously health-checked (see rng_health.h) so a
 * failed or disconnected sensor is reported instead of silently
 * producing a degraded password.
 */

#include <stdint.h>
#include <stdio.h>
#define STM32F411xE
#include "stm32f4xx.h"
#include "rng_health.h"
#include "crypto.h"

#define PASSWORD_LEN_MIN     1U
#define PASSWORD_LEN_MAX     250U
#define PASSWORD_LEN_DEFAULT 16U

char stringOut[PASSWORD_LEN_MAX + 2U];

/* Health-test state, one per ADC channel (PA0/temp, PA1/light). Each
 * channel is checked independently since they are separate physical
 * noise sources. */
static rht_state_t temp_health;
static rht_state_t light_health;

/* Set by checked_adc_read() when either channel's health test fails.
 * Once set, the current password is discarded instead of transmitted. */
static uint8_t entropy_fault = 0U;

/* --- Selectable character classes --- */
#define CHARSET_MAX_LEN 94U   /* lower(26) + upper(26) + digit(10) + symbol(32) */

static const char CHARS_LOWER[]  = "abcdefghijklmnopqrstuvwxyz";
static const char CHARS_UPPER[]  = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
static const char CHARS_DIGIT[]  = "0123456789";
static const char CHARS_SYMBOL[] = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";

/* Built once per session by build_charset(): the pool of characters the
 * current password is drawn from, and how many of them there are. */
static char charset[CHARSET_MAX_LEN];
static uint8_t charset_len;

/* Largest multiple of charset_len that fits in one entropy byte (0..256).
 * Recomputed by build_charset() whenever the charset changes; used by
 * noisy_char_from_charset() for rejection sampling (see its comment). */
static uint16_t charset_reject_threshold;

void vdg_UART_TxChar(char c) {
    while ((USART2->SR & USART_SR_TXE) == 0);
    USART2->DR = c;
}

void vdg_UART_TxString(char strOut[]) {
    uint8_t i = 0;
    while (strOut[i] != '\0') {
        vdg_UART_TxChar(strOut[i]);
        i++;
    }
}

/* Blocking single-character read: waits for one byte from the host
 * terminal on PA3 (RX). */
char vdg_UART_RxChar(void) {
    while ((USART2->SR & USART_SR_RXNE) == 0);
    return (char)USART2->DR;
}

/* Prompts the user over UART and reads a decimal password length,
 * echoing digits back as they are typed. Submitted with Enter (CR or
 * LF). A CR/LF seen before any digit is ignored rather than treated as
 * an empty submission: some USB-to-serial adapters buffer bytes for a
 * few milliseconds, so the trailing newline from the *previous*
 * yes/no answer can still be in flight when this prompt starts reading
 * - if it arrives here, it must not be mistaken for the user pressing
 * Enter with nothing typed. Out-of-range input is clamped into range. */
uint16_t prompt_password_length(void) {
    uint16_t value = 0U;
    uint8_t got_digit = 0U;
    char c;

    vdg_UART_TxString("\r\nPassword length (1-250): ");

    do {
        c = vdg_UART_RxChar();
        if ((c >= '0') && (c <= '9')) {
            got_digit = 1U;
            vdg_UART_TxChar(c);
            value = (uint16_t)((value * 10U) + (uint16_t)(c - '0'));
            if (value > PASSWORD_LEN_MAX) {
                value = PASSWORD_LEN_MAX;
            }
        }
    } while ((got_digit == 0U) || ((c != '\r') && (c != '\n')));

    if (value < PASSWORD_LEN_MIN) {
        value = PASSWORD_LEN_DEFAULT;
    }

    vdg_UART_TxString("\r\n");
    return value;
}

/* Asks a yes/no question over UART. Accepts y/Y/n/N, echoes the answer,
 * and keeps asking until a valid answer is given. Returns 1U for yes. */
uint8_t prompt_yes_no(char prompt[]) {
    char c;
    uint8_t result;

    vdg_UART_TxString(prompt);
    do {
        c = vdg_UART_RxChar();
    } while ((c != 'y') && (c != 'Y') && (c != 'n') && (c != 'N'));
    vdg_UART_TxChar(c);
    vdg_UART_TxString("\r\n");

    if ((c == 'y') || (c == 'Y')) {
        result = 1U;
    } else {
        result = 0U;
    }
    return result;
}

/* Appends one character class (a null-terminated literal) onto the end
 * of charset[], advancing charset_len. */
void append_charclass(const char class_chars[]) {
    uint8_t i = 0U;
    while (class_chars[i] != '\0') {
        charset[charset_len] = class_chars[i];
        charset_len++;
        i++;
    }
}

/* Prompts for which character classes to include (lowercase, uppercase,
 * digits, symbols), builds charset[]/charset_len from the answers, and
 * recomputes the rejection-sampling threshold for that charset size.
 * Returns 1U if at least one class was selected, 0U if every class was
 * declined - the caller must treat 0U as "cancel this generation", since
 * an empty charset has nothing to generate from. */
uint8_t build_charset(void) {
    uint8_t ok;

    charset_len = 0U;

    if (prompt_yes_no("Include lowercase a-z? (y/n): ") == 1U) {
        append_charclass(CHARS_LOWER);
    }
    if (prompt_yes_no("Include uppercase A-Z? (y/n): ") == 1U) {
        append_charclass(CHARS_UPPER);
    }
    if (prompt_yes_no("Include digits 0-9? (y/n): ") == 1U) {
        append_charclass(CHARS_DIGIT);
    }
    if (prompt_yes_no("Include symbols !@#$...? (y/n): ") == 1U) {
        append_charclass(CHARS_SYMBOL);
    }

    if (charset_len == 0U) {
        vdg_UART_TxString("No character type selected - generation cancelled.\r\n");
        ok = 0U;
    } else {
        /* Largest multiple of charset_len that is <= 256: entropy bytes
         * at or above this are discarded and resampled (same reasoning
         * as the old ENTROPY_REJECT_THRESHOLD, generalized to any
         * charset size). */
        charset_reject_threshold = (uint16_t)((256U / charset_len) * charset_len);
        ok = 1U;
    }
    return ok;
}

/* One ADC conversion on the given channel (0=temp/PA0, 1=light/PA1),
 * returns the raw 12-bit code. */
uint16_t adc_read(uint8_t channel) {
    ADC1->SQR3 = (ADC1->SQR3 & ~ADC_SQR3_SQ1) | (channel << ADC_SQR3_SQ1_Pos);
    ADC1->CR2 |= ADC_CR2_SWSTART;
    while ((ADC1->SR & ADC_SR_EOC) == 0);   /* wait for conversion */
    return ADC1->DR;
}

/* Same as adc_read(), but also feeds the raw sample into the given
 * channel's health test. Sets entropy_fault if the source looks stuck
 * or badly skewed (see rng_health.h). */
uint16_t checked_adc_read(uint8_t channel, rht_state_t *health) {
    uint16_t value = adc_read(channel);
    if (rht_check(health, value) != RHT_OK) {
        entropy_fault = 1U;
    }
    return value;
}

/* Rejection sampling (below, on the packed byte) and Von Neumann
 * debiasing (here, on individual bits) fix two different problems.
 * Rejection sampling only corrects the rounding edge case where 256 is
 * not a multiple of charset_len; it assumes the input byte is already
 * close to uniform. It is not: measured on real hardware
 * (adc_samples.csv), the raw ADC LSB is skewed as far as 83%/17% rather
 * than 50/50, and that skew survived unchanged all the way to the
 * output characters even after rejection sampling was added, because
 * rejection sampling never touches the *interior* of the accepted
 * range, only its far edge.
 *
 * Von Neumann debiasing fixes the actual skew: take two raw single-bit
 * samples from the same channel; if they differ, output the first
 * (01 -> 0, 10 -> 1); if they match (00 or 11), neither one is used and
 * the pair is discarded and retried. Whatever the true P(1) of the
 * source is, P(01) == P(10) == p*(1-p) always, so the output bit is
 * exactly unbiased - this only requires consecutive samples to be
 * roughly independent, which the same capture already confirmed
 * (H(X|previous) is within 1.4% of H(X)). */
#define MAX_VN_ATTEMPTS 64U

/* Reads one Von Neumann-debiased bit from the given ADC channel. Capped
 * at MAX_VN_ATTEMPTS retries for the same reason the rejection loop
 * below is capped: a truly stuck channel (00 or 11 forever) must not be
 * allowed to hang this function, since it might not be biased enough
 * for the raw health test to have already caught it. */
uint8_t von_neumann_bit(uint8_t channel, rht_state_t *health) {
    uint8_t a;
    uint8_t b;
    uint8_t attempts = 0U;

    do {
        a = checked_adc_read(channel, health) & 0x1U;
        b = checked_adc_read(channel, health) & 0x1U;
        attempts++;
        if (attempts >= MAX_VN_ATTEMPTS) {
            entropy_fault = 1U;
        }
    } while ((a == b) && (entropy_fault == 0U));
    return a;
}

/* Rejection sampling is only guaranteed to terminate "on average" - if
 * the source is stuck, the derived entropy byte could keep landing in
 * the rejected range forever. Capping the retry count turns that
 * failure mode into a reported fault instead of a hang. */
#define MAX_REJECTION_ATTEMPTS 64U

/* Builds one 8-bit entropy byte from 8 Von Neumann-debiased bits,
 * alternating temp/light channel per bit. Shared by
 * noisy_char_from_charset() (which maps this onto a password
 * character) and generate_salt() (which uses the raw byte directly,
 * with no charset mapping needed). */
uint8_t raw_entropy_byte(void) {
    uint8_t entropy = 0;

    for (uint8_t i = 0; i < 8U; i++) {
        uint8_t bit;
        if ((i & 0x1U) == 0U) {
            bit = von_neumann_bit(0, &temp_health);
        } else {
            bit = von_neumann_bit(1, &light_health);
        }
        entropy = (uint8_t)((entropy << 1) | bit);
    }
    return entropy;
}

/* Maps a raw entropy byte onto charset[] (built by build_charset()
 * from the user's class selection). An entropy byte at or above
 * charset_reject_threshold is discarded and resampled instead of
 * used, correcting the remaining rounding-edge bias described
 * above. */
char noisy_char_from_charset(void) {
    uint8_t entropy;
    uint8_t attempts = 0U;

    do {
        entropy = raw_entropy_byte();
        attempts++;
        if (attempts >= MAX_REJECTION_ATTEMPTS) {
            /* Entropy has been rejected too many times in a row: the
             * source is not behaving as expected even though the raw
             * health test has not (yet) caught it. Treat it the same
             * as a health-test failure so the password is discarded. */
            entropy_fault = 1U;
        }
        /* If the source is stuck (health test already failed), a stuck
         * value could keep landing in the rejected range forever - stop
         * resampling once entropy_fault is set so this never hangs; the
         * caller discards the whole password anyway when that happens. */
    } while ((entropy_fault == 0U) && ((uint16_t)entropy >= charset_reject_threshold));
    return charset[entropy % charset_len];
}

/* Builds a 32-bit salt from 4 raw entropy bytes (same debiased
 * hardware source as the password generator itself). Used to salt
 * the master-key hash so the same master key hashes differently on
 * every device/reset - see crypto.h. */
uint32_t generate_salt(void) {
    uint32_t salt = 0;

    for (uint8_t i = 0; i < 4U; i++) {
        salt = (salt << 8) | raw_entropy_byte();
    }
    return salt;
}

/* Sends one byte as two hex digits, used only by the crypto demo
 * below to show ciphertext bytes that are not printable ASCII. */
void vdg_UART_TxHexByte(uint8_t b) {
    static const char hexDigits[] = "0123456789ABCDEF";

    vdg_UART_TxChar(hexDigits[(b >> 4) & 0xFU]);
    vdg_UART_TxChar(hexDigits[b & 0xFU]);
}

/* One-shot demo proving Crypto_HashKey()/Crypto_XorProcess() work
 * end to end: salts and hashes a placeholder master key, encrypts a
 * placeholder password with that hash, then decrypts it back and
 * checks the round trip matches. Review this before it is wired to
 * a real UART-prompted master key and real stored passwords. */
void demo_crypto(void) {
    const char masterKey[] = "correct horse battery staple";
    char plaintext[] = "Hunter2!";
    uint16_t len = (uint16_t)(sizeof(plaintext) - 1U);
    uint32_t salt = generate_salt();
    uint32_t key = Crypto_HashKey(masterKey, salt);
    char roundTrip[sizeof(plaintext)];

    for (uint16_t i = 0; i < len; i++) {
        roundTrip[i] = plaintext[i];
    }

    vdg_UART_TxString("\r\n--- crypto demo ---\r\n");
    vdg_UART_TxString("salt = 0x");
    vdg_UART_TxHexByte((uint8_t)(salt >> 24));
    vdg_UART_TxHexByte((uint8_t)(salt >> 16));
    vdg_UART_TxHexByte((uint8_t)(salt >> 8));
    vdg_UART_TxHexByte((uint8_t)salt);
    vdg_UART_TxString("\r\nkey (hashed) = 0x");
    vdg_UART_TxHexByte((uint8_t)(key >> 24));
    vdg_UART_TxHexByte((uint8_t)(key >> 16));
    vdg_UART_TxHexByte((uint8_t)(key >> 8));
    vdg_UART_TxHexByte((uint8_t)key);

    Crypto_XorProcess((uint8_t *)roundTrip, len, key);
    vdg_UART_TxString("\r\nciphertext = 0x");
    for (uint16_t i = 0; i < len; i++) {
        vdg_UART_TxHexByte((uint8_t)roundTrip[i]);
    }

    Crypto_XorProcess((uint8_t *)roundTrip, len, key);
    roundTrip[len] = '\0';
    vdg_UART_TxString("\r\ndecrypted  = ");
    vdg_UART_TxString(roundTrip);
    vdg_UART_TxString("\r\n-------------------\r\n");
}

int main(void) {

    /* --- Enable GPIOA, USART2, ADC1 clocks --- */
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

    /* --- Setup PA2 (TX) + PA3 (RX) as AF7 --- */
    GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3);
    GPIOA->MODER |= (0b10 << GPIO_MODER_MODER2_Pos) | (0b10 << GPIO_MODER_MODER3_Pos);
    GPIOA->AFR[0] &= ~(GPIO_AFRL_AFSEL2 | GPIO_AFRL_AFSEL3);
    GPIOA->AFR[0] |= (7 << GPIO_AFRL_AFSEL2_Pos) | (7 << GPIO_AFRL_AFSEL3_Pos);

    /* --- Setup USART2: 115200 bps, transmit + receive --- */
    USART2->BRR = (8 << 4) | 11;
    USART2->CR1 |= USART_CR1_TE | USART_CR1_RE | USART_CR1_UE;

    /* --- Setup PA0 (NTC) + PA1 (LDR): analog input --- */
    GPIOA->MODER &= ~(GPIO_MODER_MODER0 | GPIO_MODER_MODER1);
    GPIOA->MODER |= (0b11 << GPIO_MODER_MODER0_Pos) | (0b11 << GPIO_MODER_MODER1_Pos);

    /* --- Enable ADC1 --- */
    ADC1->CR2 |= ADC_CR2_ADON;

    /* --- Sample time: channels 0+1, 28 cycles --- a short sample time
     * is intentional (a long settle time, like the original 480-cycle
     * setting, suppresses the very noise being harvested), but too
     * short leaves back-to-back conversions on the same channel
     * correlated with each other (the sample-and-hold capacitor not
     * fully re-acquiring between them), which breaks the independence
     * Von Neumann debiasing depends on. Measured on real hardware: 3
     * cycles left significant residual bias in the output (chi2=72 on
     * class balance), 15 cycles cut it substantially but not fully
     * (chi2=27) - trying 28 cycles next to see if more recovery time
     * closes the remaining gap. */
    ADC1->SMPR2 &= ~(ADC_SMPR2_SMP0 | ADC_SMPR2_SMP1);
    ADC1->SMPR2 |= (0b010U << ADC_SMPR2_SMP0_Pos) | (0b010U << ADC_SMPR2_SMP1_Pos);

    /* --- Sequence: 1 conversion at a time; channel picked in adc_read() --- */
    ADC1->SQR1 &= ~(ADC_SQR1_L);

    /* --- Reset entropy-source health tests before first use --- */
    rht_init(&temp_health);
    rht_init(&light_health);

    demo_crypto();

    while (1) {

        if (build_charset() == 0U) {
            /* Every character class was declined: nothing to generate
             * from, so skip straight back to re-asking instead of
             * prompting for a length that could never be filled. */
        } else {
            uint16_t password_len = prompt_password_length();

            entropy_fault = 0U;

            for (uint16_t i = 0; i < password_len; i++) {
                stringOut[i] = noisy_char_from_charset();
            }
            stringOut[password_len] = '\n';
            stringOut[password_len + 1U] = '\0';

            if (entropy_fault == 0U) {
                vdg_UART_TxString(stringOut);
            } else {
                /* Entropy source failed its health test partway through
                 * this password: the raw material is not trustworthy,
                 * so the password is discarded instead of transmitted. */
                vdg_UART_TxString("ENTROPY SOURCE FAULT - password discarded\n");
            }
        }
    }
}
